export const mockData = {
  "Seller Name(s)": "CELEENA AJODHA and NAIPAUL AJODHA",
  "Buyer Names(s)": "Lien Thi Bich Pham and Tuan Trong Truong",
  Address: "3134 NW 109th Ter, Sunrise, FL 33351",
  County: "Broward County",
  "Tax ID": "494119130100",
  "Purchase Price": "480,000.00",
  "Initial deposit amount": "5,000.00",
  "Additional deposit amount": "25",
  "Financing amount": "$450,000",
  "Closing Date": "days",
  "Effective Date": "09/10/22",
  "Subject to Lease": "No",
  "Contract Assignability": "No",
  "Financing Contingency": "No",
  "Purchase Money note and mortgage to seller": "No",
  "Seller Designates Agent": "No",
  "Buyer Designates Agent": "No",
  "Regional Provision": "Yes",
  "Abstract Continuation Max": "$200.00",
  "Home Warranty": "No",
  "Property Inspection Days": "N/A",
  "Additional Terms":
    "40-50 days closing.  The buyer needs to sell her property 1700 NW Terrace Plantation FL 33322 and the Seller agrees to extend the closing if necessary. With no contingencies. Seller shall pay all open and/or expired permits, liens, and code violations before the closing date.",
  "Sales Associates": "Yes",
  "Municipal Special Assessments":
    "Seller shall pay, in full, prior to or at the time of Closing, any assessment(s) allowed by the public body  to be prepaid. For any assessment(s) which the public body does not allow prepayment, OPTION (a) shall be deemed selected for such assessment(s)",
  "Other charges to buyer": null,
  "Other charges to seller": null,
  "Selling Agent": null,
  "Initial deposit date": "09/13/22",
  "Additional deposit date": "09/20/22",
  "Listing Agent": null,
  "Title Evidence Days": "5",
  "Amount Deposit": "Yes",
  "Additional Addenda": "Homeowners Assn.",
};
