export const customDatasArr = [
  { name: "Seller Name(s)", id: "check1", checked: false },
  { name: "Buyer Names(s)", id: "check2", checked: false },
  { name: "Address", id: "check3", checked: false },
  { name: "County", id: "check4", checked: false },
  { name: "Tax ID", id: "check5", checked: false },
  { name: "Purchase Price", id: "check6", checked: false },
  { name: "Initial deposit amount", id: "check7", checked: false },
  { name: "Additional deposit amount", id: "check8", checked: false },
  { name: "Financing amount", id: "check9", checked: false },
  { name: "Closing Date", id: "check10", checked: false },
  { name: "Effective Date", id: "check11", checked: false },
  { name: "Subject to Lease", id: "check12", checked: false },
  { name: "Contract Assignability", id: "check13", checked: false },
  { name: "Financing Contingency", id: "check14", checked: false },
  {
    name: "Purchase Money note and mortgage to seller",
    id: "check15",
    checked: false,
  },
  { name: "Seller Designates Agent", id: "check16", checked: false },
  { name: "Buyer Designates Agent", id: "check17", checked: false },
  { name: "Regional Provision", id: "check18", checked: false },
  { name: "Abstract Continuation Max", id: "check19", checked: false },
  { name: "Home Warranty", id: "check20", checked: false },
  { name: "Property Inspection Days", id: "check21", checked: false },
  { name: "Additional Terms", id: "check22", checked: false },
  { name: "Listing Agent", id: "check23", checked: false },
  { name: "Selling Agent", id: "check24", checked: false },
  { name: "Municipal Special Assessments", id: "check25", checked: false },
  { name: "Other charges to buyer", id: "check26", checked: false },
  { name: "Other charges to seller", id: "check27", checked: false },
  { name: "Title Evidence Days", id: "check28", checked: false },
  { name: "Initial deposit date", id: "check29", checked: false },
  { name: "Additional deposit date", id: "check30", checked: false },
  { name: "Sales Associates", id: "check31", checked: false },
  { name: "Amount Deposit", id: "check32", checked: false },
  { name: "Additional Addenda", id: "check33", checked: false },
];
